version: '3'

services:
  app:
    build: ./app
    command: python manage.py run -h 0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db
  celery_beat:
    build: 
      context: ./
      dockerfile: ./worker/Dockerfile
    command: celery -A worker beat --loglevel=info
    env_file:
      - ./.env.dev    
    depends_on:
      - celery_worker
  celery_worker:
    build: 
      context: ./
      dockerfile: ./worker/Dockerfile
    command: celery -A worker worker
    env_file:
      - ./.env.dev    
    depends_on:
      - app
      - rabbit      
  rabbit:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=test_user
      - RABBITMQ_DEFAULT_PASS=test_password
    ports:
      - "5672:5672"
